# This is a basic workflow to help you get started with Actions

name: Event

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    runs-on: ubuntu-22.04
    continue-on-error: true
    env:
      AA: coucou
    steps:
      - run: echo ${{ vars.toto }}
      - run: echo ${{ vars.TOTO }}
      - run: echo $AA
      - run: echo $TOTO
      - run: echo $ENV_AA
      - run: echo ${{ env.AA }}
      - run: echo ${{ env.aa }}
  
      
  build:
    runs-on: ubuntu-22.04
    needs: [init]
    if: ${{ needs.init.result == 'success' }}
    steps:
      - name: Run a one-line script
        run: echo "coucou"  
  result:
    runs-on: ubuntu-22.04
    needs: [build]
    env: 
      CTX: ${{toJson(needs)}}
    if: ${{ !failure() }}  
    steps:
      - name: Run a one-line script
        run: echo $CTX
