# This is a basic workflow to help you get started with Actions

name: Event

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [18, 20]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - uses: actions/checkout@v3
      - name: Run a one-line script
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "oss=${{matrix.os}}" >> $GITHUB_OUTPUT
  result:
    runs-on: ubuntu-22.04
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Display context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo "$NEEDS_CONTEXT"
    needs: [build]
