# This is a basic workflow to help you get started with Actions

name: Event

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "test=boum" >> $GITHUB_OUTPUT
        id: step1
    outputs:
      output1: ${{ steps.step1.outputs.test }} 
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [18, 20]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "oss=${{matrix.os}}" >> $GITHUB_OUTPUT
        id: buildstep
    outputs:
      output1: ${{ steps.buildstep.outputs.oss }}    
  result:
    runs-on: ubuntu-22.04
    needs: [build]
    if: 1 == 2
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Display context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs.build) }}
        run: echo "$NEEDS_CONTEXT"
      - name: Display context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs.test) }}
        run: echo "$NEEDS_CONTEXT"
  afterSkip:
    runs-on: ubuntu-22.04
    needs: [result,test]
    if: always()
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  last:
    runs-on: ubuntu-22.04
    needs: [afterSkip]
    steps:
      - run: echo End 
