on: [push]

jobs:
  toto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  hello_world_job:
    runs-on: ubuntu-latest
    environment: prod
    name: A job to say hello
    needs: [toto]
    steps:
      - uses: actions/checkout@v4
        id: checkout-aa
      - run: echo "MYOUTPUT=${{ vars.ENV_VAR}}" >> $GITHUB_OUTPUT 
        id: poupou_plipli
      - name: Display github context
        run: |
          echo "Steps context:"
          echo "${TITI}"
        shell: bash
        env:
         TITI: ${{ toJson(steps) }}
      - id: foo
        uses: sguiheux/hello-world-composite-action@v14
        with:
          who-to-greet: 'Mona the Octocat'
          variables: ${{ env.GITHUB }}
          event: ${{ env.EVENT }}
        env:
          GITHUB: ${{ toJson(vars) }}
          EVENT: ${{ toJson(github.event) }}
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
