on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    environment: prod
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ vars.ENV_VAR}} - ${{ secrets.ENV_SECRET}}"
      - id: foo
        uses: sguiheux/hello-world-composite-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
